### ISSUE TITLE
Maintenance command

### ISSUE THREAD

**Issue by ReferTV** [Elytrium/FastMOTD#8]
/maintenance toggle, /maintenance on and  /maintenance off commands

**Comment by SkyWatcher2019** [comment]
yes pls

**Comment by lightumcc** [comment]
Try to use the API of an existing maintenance plugin so that this plugin does not conflict with it.
Plugin link: https://forums.papermc.io/threads/maintenance-a-greatly-customizable-maintenance-plugin.7
API link: https://github.com/kennytv/Maintenance
By the way, I cannot access your discord link, SSL_PROTOCOL_ERROR
